version: "3.8"
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
